- name: show OS version
  debug:
    msg: "OS = {{ ansible_os_family }} "

- name: check that OS = Redhat
  fail:
    msg: "This playbook only supports Ubuntu"
  when: ansible_os_family != "Debian"

- name: Install Java Runtime Environment
  apt: name=default-jre state=present

- name: Install git
  apt: name=git state=present

- name: copy root user directories
  copy:
    src: files/{{ item }}
    dest: /
    group: "root"
    owner: "root"
  with_items:
    - "root"

- name: installation configuration template
  template:
    src: "install_config.sh"
    dest: "/root/install-scripts/install_config.sh"
    owner: "root"
    group: "root"
    mode: 0755

- name: mock init script template
  template:
    src: "run_mock.sh"
    dest: "/root/install-scripts/run_mock.sh.template"
    owner: "root"
    group: "root"
    mode: 0655

- name: set file permissions
  file:
    mode: 0755
    path: "/root/install-scripts/{{ item }}"
  with_items:
    - "install_soapui.sh"
    - "install_mock.sh"
    - "install_config.sh"
    - "install_xroad_python_tests.sh"

- name: install SoapUI
  shell: ./install_soapui.sh
  args:
    chdir: /root/install-scripts/

- name: download X-Road Python tests
  shell: ./install_xroad_python_tests.sh
  args:
    chdir: /root/install-scripts/

- name: install mock service
  shell: ./install_mock.sh
  args:
    chdir: /root/install-scripts/

- name: start mock service
  shell: /etc/init.d/mock-service start
  args:
    chdir: /root/

