- name: show OS version
  debug:
    msg: "OS = {{ ansible_os_family }} "

- name: check that OS = Redhat
  fail:
    msg: "This playbook only supports Ubuntu"
  when: ansible_os_family != "Debian"

- name: nginx-light
  apt: name=nginx-light state=present

- name: sshd
  apt: name=openssh-server state=present

- name: git
  apt: name=git state=present

- name: copy root user directories
  copy:
    src: files/{{ item }}
    dest: /
    group: "root"
    owner: "root"
  with_items:
    - "etc"
    - "usr"

- name: restart nginx
  service:
    name: nginx
    state: restarted

# Default password for user is: secret
- user:
    name: "{{ ssh_username }}"
    password: "{{ ssh_password }}"

- name: Create 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Add sudoers users to wheel group
  user:
    name: "{{ item }}"
    groups: wheel
    append: yes
  with_items:
    - user

- name: check if git repository has already been downloaded
  stat: path="/root/{{ xroad_python_tests_root }}"
  register: git_repo
  ignore_errors: True

- name: Remove git repository if it exists
  file:
    state: absent
    path: "/root/{{ xroad_python_tests_root }}"
  when: git_repo.stat.exists

- name: download X-Road Python tests
  shell: git clone {{ xroad_python_tests_git_path }}
  args:
    chdir: /root/

- name: copy WSDL files to nginx directory
  shell: cp -R /root/{{ xroad_mock_wsdl_path }}* /usr/share/nginx/html/www/

- name: chmod WSDL files
  shell: chmod 755 -R /usr/share/nginx/html/www/*
  
- name: chown WSDL files
  shell: chown user:user -R /usr/share/nginx/html/www/*
