quarkus:
  application:
    name: X-Road Signer Console
#  vault:
#    url: "${XROAD_SECRET_STORE_SCHEME:http}://${XROAD_SECRET_STORE_HOST:127.0.0.1}:${XROAD_SECRET_STORE_PORT:8200}"
#    authentication:
#      client-token: "${XROAD_SECRET_STORE_TOKEN}"
#    devservices:
#      enabled: false
  config:
    locations:
      - xroad-common.yaml
      - xroad-logging.yaml
      - /etc/xroad/conf.d/local.yaml

  log:
    console:
      enabled: false
    file:
      enabled: true
      path: /var/log/xroad/signer-console.log
    syslog:
      enabled: true
      app-name: signer-console
      format: "%-5p [X-Road Signer Console] %d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} - %m"

"%test":
  quarkus:
    log:
      file:
        enabled: false
