---
ss_modules:
  monitor:
    dir: service/monitor/monitor-application
    build: build
    target: /usr/share/xroad/jlib/monitor
    service: xroad-monitor
  proxy:
    dir: service/proxy/proxy-application
    build: build
    target: /usr/share/xroad/jlib/proxy
    service: xroad-proxy
  configuration-client:
    dir: service/configuration-client/configuration-client-application
    build: build
    target: /usr/share/xroad/jlib/configuration-client
    service: xroad-confclient
  backup-manager:
    dir: service/backup-manager/backup-manager-application
    build: build
    target: /usr/share/xroad/jlib/backup-manager
    service: xroad-backup-manager
  proxy-ui-api:
    dir: security-server/admin-service/application
    build: build
    lib: proxy-ui-api-1.0.jar
    target: /usr/share/xroad/jlib
    service: xroad-proxy-ui-api
  ds-control-plane:
    dir: service/ds-control-plane/ds-control-plane-application
    build: build
    target: /usr/share/xroad/jlib/ds-control-plane
    service: xroad-ds-control-plane
  ds-data-plane:
    dir: service/ds-control-plane/ds-data-plane-application
    build: build
    target: /usr/share/xroad/jlib/ds-data-plane
    service: xroad-ds-data-plane