---
- name: configure slave serverconf db
  import_tasks: serverconf_slave_db.yml

- name: fix permissions
  file:
    path: /etc/xroad/autologin
    owner: xroad
    state: file
  ignore_errors: yes

- name: do initial configuration sync
  become_user: xroad
  become: yes
  command: rsync -e "ssh -o StrictHostKeyChecking=no" -aqz --delete-delay --exclude "/db.properties" --exclude "/conf.d/node.ini" --exclude "*.tmp" --exclude "/postgresql" --exclude "/nginx" --exclude "/backup.d" --exclude "/gpghome" "{{ xroad_slave_ssh_user }}@{{ master_host }}":/etc/xroad/ /etc/xroad/

- name: install configuration sync
  include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: setup sync log rotation
  copy:
      src: "xroad-slave-sync.logrotate"
      dest: "/etc/logrotate.d/xroad-slave-sync"

- name: enable slave role for node
  ini_file: dest=/etc/xroad/conf.d/node.ini
            section=node
            option=type
            value=slave
            create=true
            mode=0640
            owner=xroad
            group=xroad

- name: start services
  service:
      name: "{{ item }}"
      state: started
  with_items:
      - xroad-proxy
      - xroad-confclient
      - xroad-signer
      - xroad-proxy-ui-api

- name: remove UI editor groups
  group:
      name: "{{ item }}"
      state: absent
  with_items: "{{ ui_editor_groups }}"
  tags: remove_editor_groups
