quarkus:
  application:
    name: ds-data-plane
  config:
    locations:
      - xroad-common.yaml
      - xroad-logging.yaml
  log:
    level: INFO
    category:
      "EDC":
        level: DEBUG

"%native":
  quarkus:
    config:
      locations:
        - xroad-common.yaml
        - xroad-logging.yaml
        - /etc/xroad/conf.d/local-tls.yaml
        - /etc/xroad/conf.d/local.yaml
        - /etc/xroad/db.properties
    log:
      console:
        enabled: false
      file:
        enabled: true
        path: /var/log/xroad/ds-data-plane.log

web:
  http:
    protocol:
      port: 8283
      path: /api/dsp

edc:
  participant:
    id: participantContextId
  dpf:
    selector:
      url: https://127.0.0.1:9192/control/v1/dataplanes
  hostname: host.docker.internal
  component:
    id: DSP-compatibility-test
  transfer:
    proxy:
      token:
        signer:
          privatekey:
            alias: private-key
        verifier:
          publickey:
            alias: public-key
  datasource:
    default:
      url: ${xroad.db.ds-data-plane.hibernate.connection.url}
      user: ${xroad.db.ds-data-plane.hibernate.connection.username}
      password: ${xroad.db.ds-data-plane.hibernate.connection.password}
    #      slot: edc_cdc_slot
  sql:
    schema:
      autocreate: true
  iam:
    oauth2:
      jwks:
        url: https://example.com/jwks
      issuer: test-issuer
