---
- name: autologin configuration
  template:
    src: "xroad-autologin.j2"
    dest: "/etc/xroad/autologin"
    owner: root
    group: xroad
    mode: 0640
    force: no

- name: install autologin
  package: name=xroad-autologin state=latest

- name: enable autologin service
  service: name=xroad-autologin enabled=yes
