---
- name: install xroad-autologin
  yum:
      name: xroad-autologin
      state: latest
      update_cache: yes

- name: enable xroad-autologin service
  service: name=xroad-autologin enabled=yes

