---
common_modules:
  common-util:
    dir: common/common-util
    build: build
    lib: common-util-1.0.jar
    target: /usr/share/xroad/jlib
  signer:
    dir: signer
    build: build
    lib: signer-1.0.jar
    target: /usr/share/xroad/jlib
  signer-console:
    dir: signer-console
    build: build
    lib: signer-console-1.0.jar
    target: /usr/share/xroad/jlib
