---
cs_modules:
  center-ui:
    dir: center-ui
    build: warble
    lib: center-ui.war
    target: /usr/share/xroad/jlib/webapps
  center-service-war:
    dir: center-service
    build: warble
    lib: center-service.war
    target: /usr/share/xroad/jlib/webapps
  center-service:
    dir: center-service
    build: build
    lib: center-service-1.0.jar
    target: /usr/share/xroad/jlib
