---
ss_modules:
  monitor:
    dir: service/monitor/monitor-application
    build: build
    lib: monitor-1.0.jar
    target: /usr/share/xroad/jlib
  proxy:
    dir: proxy/application
    build: build
    lib: proxy-1.0.jar
    target: /usr/share/xroad/jlib
    service: xroad-proxy
  addon-proxy:
    dir: addons/proxymonitor/metaservice
    build: build
    lib: proxymonitor-metaservice-1.0.jar
    target: /usr/share/xroad/jlib/addon/proxy
  addon-message-log-archiver:
    dir: service/message-log-archiver/message-log-archiver-application
    build: build
    lib: messagelog-archiver.jar
    target: /usr/share/xroad/jlib/addon/proxy
    service: xroad-addon-messagelog
  addon-metaservice:
    dir: addons/metaservice
    build: build
    lib: metaservice-1.0.jar
    target: /usr/share/xroad/jlib/addon/proxy
  configuration-client:
    dir: service/configuration-client/configuration-client-application
    build: build
    lib: configuration-client-1.0.jar
    target: /usr/share/xroad/jlib
    service: xroad-confclient
  proxy-ui-api:
    dir: security-server/admin-service/application
    build: build
    lib: proxy-ui-api-1.0.jar
    target: /usr/share/xroad/jlib
    service: xroad-proxy-ui-api
