eab-credentials:
  certificate-authorities:
    'Test CA':
      mac-key-base64-encoded: true
      members:
        'DEV:COM:1234':
          kid: 1
          mac-key: secretkey
account-keystore-password: testPassword1234