quarkus:
  application:
    name: op-monitor-daemon
  config:
    locations:
      - xroad-common.yaml
      - xroad-logging.yaml
  scheduler:
    start-mode: forced
    enabled: true

xroad:
  op-monitor:
    tls:
      certificate-provisioning:
        common-name: ${XROAD_HOST:localhost}
        ip-subject-alt-names:
          - 127.0.0.1
  db:
    op-monitor:
      hibernate:
        hikari.dataSource.ApplicationName: ${quarkus.application.name}

"%native":
  quarkus:
    config:
      locations:
        - /etc/xroad/conf.d/local.yaml
        - /etc/xroad/db.properties
    log:
      file:
        enabled: true
        path: /var/log/xroad/op-monitor.log

"%containerized":
  xroad:
    op-monitor:
      rpc:
        listen-address: 0.0.0.0
