spring:
  config:
    import:
      - classpath:/xroad-common.yaml
  servlet:
    multipart.enabled: false
server:
  error:
    whitelabel:
      enabled: false
  jetty:
    connection-idle-timeout: 15s
    threads:
      max-queue-capacity: 10000
      max: 32
      acceptors: 2
  servlet:
    jsp:
      registered: false
    session:
      tracking-modes:
  port: 8084
  ssl:
    enabled: true
    ciphers: TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    protocol: TLS
    enabled-protocols: TLSv1.2,TLSv1.3
    bundle: management-service # Use TLS key & certificate provided by ManagementServiceSslBundleRegistrar
  address: 127.0.0.1
  forward-headers-strategy: native

xroad:
  registration-service:
    rate-limit-enabled: true
    rate-limit-requests-per-second: -1
    rate-limit-requests-per-minute: 10
    rate-limit-cache-size: 10_000
    rate-limit-expire-after-access-minutes: 2
    api-base-url: https://127.0.0.1:4000/api/v1
    tls:
      certificate-provisioning:
        common-name: ${XROAD_HOST:localhost}
        ip-subject-alt-names:
          - 127.0.0.1
