# This file contains the full list of privileges used in UI authorization.
# Each privilege is mapped to a list of roles that it belongs to.

# roles:
#   - xroad-security-officer
#   - xroad-registration-officer
#   - xroad-service-administrator
#   - xroad-system-administrator
#   - xroad-securityserver-observer



- init_config: [xroad-system-administrator]
- view_clients: [xroad-security-officer, xroad-registration-officer, xroad-service-administrator, xroad-securityserver-observer]
-   add_client: [xroad-registration-officer]
-   send_client_reg_req: [xroad-registration-officer]
-   send_owner_change_req: [xroad-registration-officer]
-   view_client_details_dialog: [xroad-registration-officer, xroad-service-administrator, xroad-securityserver-observer]
-     send_client_del_req: [xroad-registration-officer]
-     delete_client: [xroad-registration-officer]
-     view_client_local_groups: [xroad-service-administrator, xroad-securityserver-observer]
-       add_local_group: [xroad-service-administrator]
-       edit_local_group_desc: [xroad-service-administrator]
-       edit_local_group_members: [xroad-service-administrator]
-       delete_local_group: [xroad-service-administrator]
-     view_client_services: [xroad-service-administrator, xroad-securityserver-observer]
-       add_wsdl: [xroad-service-administrator]
-       add_openapi3: [xroad-service-administrator]
-       add_openapi3_endpoint: [xroad-service-administrator]
-       enable_disable_wsdl: [xroad-service-administrator]
-       edit_wsdl: [xroad-service-administrator]
-       edit_openapi3: [xroad-service-administrator]
-       edit_openapi3_endpoint: [xroad-service-administrator]
-       refresh_wsdl: [xroad-service-administrator]
-       refresh_openapi3: [xroad-service-administrator]
-       delete_wsdl_missing_services: [xroad-service-administrator]
-       delete_wsdl: [xroad-service-administrator]
-       delete_endpoint: [xroad-service-administrator]
-       edit_service_params: [xroad-service-administrator]
-       view_service_acl: [xroad-service-administrator, xroad-securityserver-observer]
-       edit_service_acl: [xroad-service-administrator]
-       import_export_service_acl: [xroad-service-administrator]
-       export_client_services_acl: [xroad-service-administrator]
-     view_client_acl_subjects: [xroad-service-administrator, xroad-securityserver-observer]
-       view_acl_subject_open_services: [xroad-service-administrator, xroad-securityserver-observer]
-         edit_acl_subject_open_services: [xroad-service-administrator]
-     view_client_internal_certs: [xroad-service-administrator, xroad-registration-officer, xroad-securityserver-observer]
-       view_client_internal_cert_details: [xroad-service-administrator, xroad-registration-officer, xroad-securityserver-observer]
-       add_client_internal_cert: [xroad-service-administrator, xroad-registration-officer]
-       delete_client_internal_cert: [xroad-service-administrator, xroad-registration-officer]
-       view_client_internal_connection_type: [xroad-service-administrator, xroad-registration-officer, xroad-securityserver-observer]
-       edit_client_internal_connection_type: [xroad-service-administrator, xroad-registration-officer]
-       view_proxy_internal_cert: [xroad-service-administrator, xroad-registration-officer, xroad-securityserver-observer]
-       export_proxy_internal_cert: [xroad-service-administrator, xroad-registration-officer]
- view_keys: [xroad-security-officer, xroad-registration-officer, xroad-system-administrator, xroad-securityserver-observer]
-   activate_token: [xroad-security-officer, xroad-system-administrator]
-   deactivate_token: [xroad-security-officer, xroad-system-administrator]
-   generate_key: [xroad-security-officer, xroad-registration-officer]
-   delete_key: [xroad-security-officer, xroad-registration-officer]
-   generate_auth_cert_req: [xroad-security-officer]
-   generate_sign_cert_req: [xroad-security-officer, xroad-registration-officer]
-   generate_internal_cert_req: [xroad-security-officer]
-   import_auth_cert: [xroad-security-officer]
-   import_sign_cert: [xroad-security-officer, xroad-registration-officer]
-   activate_disable_auth_cert: [xroad-security-officer]
-   activate_disable_sign_cert: [xroad-security-officer, xroad-registration-officer]
-   send_auth_cert_reg_req: [xroad-security-officer]
-   send_auth_cert_del_req: [xroad-security-officer]
-   delete_auth_cert: [xroad-security-officer]
-   delete_sign_cert: [xroad-security-officer, xroad-registration-officer]
-   delete_auth_key: [xroad-security-officer]
-   delete_sign_key: [xroad-security-officer, xroad-registration-officer]
-   edit_keytable_friendly_names: [xroad-security-officer, xroad-registration-officer, xroad-system-administrator]
- view_sys_params: [xroad-security-officer, xroad-system-administrator, xroad-securityserver-observer]
-   view_anchor: [xroad-security-officer, xroad-system-administrator, xroad-securityserver-observer]
-     download_anchor: [xroad-security-officer, xroad-system-administrator]
-     upload_anchor: [xroad-security-officer]
-   view_tsps: [xroad-security-officer, xroad-system-administrator, xroad-securityserver-observer]
-     add_tsp: [xroad-security-officer]
-     delete_tsp: [xroad-security-officer]
-   view_internal_ssl_cert: [xroad-security-officer, xroad-system-administrator, xroad-securityserver-observer]
-     export_internal_ssl_cert: [xroad-security-officer, xroad-system-administrator]
-     import_internal_ssl_cert: [xroad-security-officer, xroad-system-administrator]
-     generate_internal_ssl: [xroad-security-officer, xroad-system-administrator]
-     generate_internal_ssl_csr: [xroad-security-officer, xroad-system-administrator]
- backup_configuration: [xroad-system-administrator]
- diagnostics: [xroad-system-administrator, xroad-securityserver-observer]
- restore_configuration: [xroad-system-administrator]
