---
# SoapUI installation
soapui_download_path: https://b537910400b7ceac4df0-22e92613740a7dd1247910134033c0d1.ssl.cf5.rackcdn.com/soapui/5.3.0/SoapUI-5.3.0-linux-bin.tar.gz
soapui_install_path: /home/jenkins/SoapUI-5.3.0/
soapui_archive_filename: SoapUI-x64.tar.gz

# PyCharm installation
pycharm_download_path: https://download.jetbrains.com/python/pycharm-community-2017.1.4.tar.gz
pycharm_archive_filename: pycharm.tar.gz

# Used for xroad-python-tests
xroad_python_tests_git_path: https://set-this-url
xroad_python_tests_local_path: /home/jenkins/
xroad_python_tests_root: X-Road-tests
xroad_python_tests_path: X-Road-tests/common/xrd-automated-tests/
xroad_mock_service_path: X-Road-tests/common/xrd-automated-tests/mock/mock_service/
xroad_mock_wsdl_path: X-Road-tests/common/xrd-automated-tests/mock/service_wsdl/
xroad_mock_run_command: bin/mockservicerunner.sh -s soapui-settings.xml testservice-soapui-project.xml
