container_ports:
  frontend:
    connect: "tcp:127.0.0.1:4000"
    listen: "tcp:0.0.0.0:{{ 3200 + (groups['ss_servers'].index(inventory_hostname) * 100) }}"
    type: proxy
  proxy_http:
    connect: "tcp:127.0.0.1:8080"
    listen: "tcp:0.0.0.0:{{ 3210 + (groups['ss_servers'].index(inventory_hostname) * 100) }}"
    type: proxy
  database:
    connect: "tcp:127.0.0.1:5432"
    listen: "tcp:0.0.0.0:{{ 3220 + (groups['ss_servers'].index(inventory_hostname) * 100) }}"
    type: proxy
  proxy:
    connect: "tcp:127.0.0.1:5500"
    listen: "tcp:0.0.0.0:{{ 3230 + (groups['ss_servers'].index(inventory_hostname) * 100) }}"
    type: proxy
  proxy_ocsp:
    connect: "tcp:127.0.0.1:5577"
    listen: "tcp:0.0.0.0:{{ 3240 + (groups['ss_servers'].index(inventory_hostname) * 100) }}"
    type: proxy
  proxy_debug:
    connect: "tcp:127.0.0.1:9999"
    listen: "tcp:0.0.0.0:{{ 3290 + (groups['ss_servers'].index(inventory_hostname) * 100) }}"
    type: proxy
  signer_debug:
    connect: "tcp:127.0.0.1:9998"
    listen: "tcp:0.0.0.0:{{ 3291 + (groups['ss_servers'].index(inventory_hostname) * 100) }}"
    type: proxy
  proxy_ui_debug:
    connect: "tcp:127.0.0.1:9997"
    listen: "tcp:0.0.0.0:{{ 3292 + (groups['ss_servers'].index(inventory_hostname) * 100) }}"
    type: proxy
  conf_client_debug:
    connect: "tcp:127.0.0.1:9996"
    listen: "tcp:0.0.0.0:{{ 3293 + (groups['ss_servers'].index(inventory_hostname) * 100) }}"
    type: proxy
  backup_manager_debug:
    connect: "tcp:127.0.0.1:9995"
    listen: "tcp:0.0.0.0:{{ 3294 + (groups['ss_servers'].index(inventory_hostname) * 100) }}"
    type: proxy