test-framework:
  junit:
    parallel-enabled: true
  component-scan:
    additional-packages:
      - org.niis.xroad.cs.test
  cucumber:
    glue: "org.niis.xroad.cs.test,org.niis.xroad.test.framework"
    filter-tags: "not @Skip"

"%cli":
  test-framework:
    working-dir: "test-framework-working-dir/"
    resource-dir: "test-framework-working-dir/resources/"
    allure:
      results-directory: "test-framework-working-dir/allure-results"
