---
# This playbook compiles X-Road and installs the compiled packages to the defined host inventory

- name: Initialize LXD servers
  hosts: lxd_servers
  strategy: free
  roles:
    - init-lxd
  tags:
    - init

- name: Perform RHEL support check
  hosts: ss_servers
  become: true
  become_user: root
  any_errors_fatal: true
  strategy: free
  tasks:
    - name: RHEL-support check
      fail:
        msg: "Variant '{{ variant }}' does not support RHEL-servers"
      when:
        - (variant is defined and variant == "ee")
        - ansible_os_family == "RedHat"

- name: Run compilation tasks
  hosts: compile_servers
  strategy: free
  roles:
    - role: compile
  tags:
    - compile

- name: Build packages
  hosts: compile_servers
  strategy: free
  roles:
    - role: build-packages
  tags:
    - build-packages

- name: Apply dev env configuration
  hosts: ss_servers, cs_servers
  become: true
  strategy: free
  roles:
    - init-dev-configuration

- name: Configure local repositories
  hosts: ss_servers, cs_servers, cp_servers
  strategy: free
  pre_tasks:
    - name: Check host connectivity
      ping:
    - name: Show target hosts
      debug:
        msg: "Target hosts in group: {{ groups['ss_servers'] + groups['cs_servers'] + groups['cp_servers'] }}"
  roles:
    - packages-to-local-repo

- name: Install CS servers
  hosts: cs_servers
  become: true
  strategy: free
  roles:
    - xroad-cs
  tags:
    - cs
    - install
  vars_files:
    - vars_files/local_repo.yml
    - vars_files/cs_database.yml

- name: Install CP servers
  hosts: cp_servers
  become: true
  strategy: free
  roles:
    - xroad-cp
  tags:
    - cp
    - install
  vars_files:
    - vars_files/local_repo.yml

- name: Install CA servers
  hosts: ca_servers
  become: true
  strategy: free
  roles:
    - xroad-ca
  tags:
    - ca
    - install
      
- name: Configure HW tokens (SoftHSM2) for SS
  hosts: ubuntu_hsm_ss
  become: true
  strategy: free
  tags:
    - ss
    - hwtokens
  vars:
    hwtoken_label: "x-road-softhsm2"
    hwtoken_so_pin: "1234"
    hwtoken_user_pin: "Secret1234"
  vars_files:
    - vars_files/local_repo.yml
  tasks:
    - name: Run ubuntu_hsm_ss hwtoken tasks
      include_role:
        name: xroad-ss
        tasks_from: hwtokens.yml

- name: Install SS servers
  hosts: ss_servers
  become: true
  become_user: root
  strategy: free
  roles:
    - xroad-ss
    - xroad-autologin
  vars:
    xroad_autologin_pin: "Secret1234"
    hwtoken_id: "31"
    hwtoken_user_pin: "Secret1234"
  tags:
    - ss
    - install
  vars_files:
    - vars_files/local_repo.yml
    - vars_files/ss_database.yml
  tasks:
    - name: Ensure xroad-autologin installed
      package:
        name: xroad-autologin
        state: present

    - name: Enable and start autologin service
      service:
        name: xroad-autologin
        enabled: yes
        state: started

- name: Install IS servers
  hosts: is_servers
  become: true
  strategy: free
  roles:
    - xroad-is
  tags:
    - is
    - install

- name: Install Hurl servers
  hosts: hurl_servers
  become: true
  strategy: free
  roles:
    - xroad-hurl
  tags:
    - hurl