- name: show OS version
  debug:
    msg: "OS = {{ ansible_os_family }} "

- name: check that OS = Redhat
  fail:
    msg: "This playbook only supports Ubuntu"
  when: ansible_os_family != "Debian"

- name: Install git
  apt: name=git state=present

- stat:
    path: "{{ xroad_python_tests_local_path }}"
  register: dir
  
- stat:
    path: "{{ xroad_python_tests_local_path }}{{ xroad_python_tests_root }}"
  register: git_dir
  
- name: create local X-Road test directory
  file:
    path: "{{ xroad_python_tests_local_path }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0775
    recurse: yes
  when: dir.stat.exists == False

- name: download X-Road Python tests
  shell: git clone {{ xroad_python_tests_git_path }}
  args:
    chdir: "{{ xroad_python_tests_local_path }}"
  when: git_dir.stat.exists == False

- name: copy root user directories
  copy:
    src: files/{{ item }}
    dest: /
    group: "root"
    owner: "root"
  with_items:
    - "root"

- name: installation configuration template
  template:
    src: "install_config.sh"
    dest: "/root/install-scripts/install_config.sh"
    owner: "root"
    group: "root"
    mode: 0755

- name: set file permissions
  file:
    mode: 0755
    path: "/root/install-scripts/{{ item }}"
  with_items:
    - "install_soapui.sh"
    - "install_pycharm.sh"
    - "install_config.sh"

- name: install SoapUI
  shell: ./install_soapui.sh
  args:
    chdir: /root/install-scripts/

- name: copy SoapUI desktop shortcut
  copy:
    src: /root/install-scripts/SoapUI.desktop
    dest: /home/jenkins/Desktop/
    group: "jenkins"
    owner: "jenkins"
    mode: 0755

- name: install PyCharm
  shell: ./install_pycharm.sh
  args:
    chdir: /root/install-scripts/

- name: copy PyCharm desktop shortcut
  copy:
    src: /root/install-scripts/PyCharm.desktop
    dest: /home/jenkins/Desktop/
    group: "jenkins"
    owner: "jenkins"
    mode: 0755

