fullnameOverride: db-serverconf
image:
  repository: bitnamilegacy/postgresql
  tag: "16.6.0"
auth:
  database: serverconf
  username: serverconf
  password: secret
  enablePostgresUser: true
  postgresPassword: admin_secret
primary:
  resources:
    requests:
      memory: 64Mi
    limits:
      memory: 256Mi
