server:
  address: 0.0.0.0
  ssl:
    enabled: false

spring:
  cloud:
    vault:
      enabled: false

xroad:
  common-rpc:
    use-tls: false
  management-service:
    api-base-url: http://mock-server:1080

logging:
  level:
    ROOT: INFO
    org:
      springframework: INFO
