---
debug: true

spring:
  cache:
    type: none
  jpa:
    hibernate:
      ddl-auto: none #TODO this should be removed once schema is stable.
    show-sql: true

cache:
  simple:
    ttl: -1

server:
  ssl:
    enabled: false
