quarkus:
  application:
    name: softtoken-signer
  config:
    locations:
      - xroad-common.yaml
      - xroad-logging.yaml
  scheduler:
    start-mode: forced
    enabled: true
  log:
    category:
      "io.grpc":
        level: "INFO"

"%containerized":
  xroad:
    softtoken-signer:
      rpc:
        listen-address: 0.0.0.0

"%test":
  quarkus:
    log:
      file:
        enabled: false
